#pragma once

#define IOCTL_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_SEND_MOUSE_INPUT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_WRITE_ACCESS)

typedef struct _READ_MEMORY_REQUEST {
    ULONG_PTR pid;
    ULONG_PTR address;
    SIZE_T size;
} READ_MEMORY_REQUEST, *PREAD_MEMORY_REQUEST;

typedef struct _SEND_INPUT_REQUEST {
    LONG deltaX;
    LONG deltaY;
} SEND_INPUT_REQUEST, *PSEND_INPUT_REQUEST;
